server:
  port: 80
spring:
  application:
    name: cloud-consumer-order
  cloud:
    consul:
      # consul注册中心地址
      host: 127.0.0.1
      port: 8500
      discovery:
#        hostname: 192.168.0.112
        service-name: ${spring.application.name}